# Generated by Django 3.2.6 on 2021-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='checkout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
