# Generated by Django 3.2.6 on 2021-08-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agenda_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='limpeza',
        ),
    ]
